config/routes.rb
Reddit::Application.routes.draw do
  resources :users
  resource :session
  resources :links
  resources :comments
  resources :subs
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :parent_comment_id, :link_id

  validates :link_id, :presence => true

  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url, :body, :user_id

  validates :title, :url, :user_id, :presence => true
  # before_validation :valid_url_format

  has_many :comments
  has_many :subs, through: :link_subs
  belongs_to :user

  def comments_by_parent_id
    hash = Hash.new
    comments = Comment.find_by_link_id(self.id)
    comments_dup = comments.dup
    until comments_dup.empty?
      comments.each do |comment|
        if comment.parent_comment_id.nil?
          hash[comment_id] = []
        else
          hash[comment_id] = []
          hash[comment.parent_comment_id] << comment_id
        end
      end
    end
    hash
  end

  private

  def valid_url_format

  end

end

app/models/link_sub.rb
class LinkSub < ActiveRecord::Base
  attr_accessible :sub_id, :link_id

  belongs_to :sub
  belongs_to :link
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :name, :moderator_id

  validates :name, :moderator_id, presence: true
  validates :name, uniqueness: true

  has_many :links, :through => :link_subs

  belongs_to(
    :moderator,
    :foreign_key => :moderator_id,
    :class_name => 'User'
  )

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'bcrypt'

  attr_accessible :username, :password, :email
  attr_reader :password

  validates :username, :session_token, :email, presence: true
  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :username, :email, uniqueness: true
  validates :password, length: { minimum: 6, :allow_nil => true }

  before_validation :ensure_session_token

  has_many(
    :subs,
    :primary_key => :id,
    :foreign_key => :moderator_id,
    :class_name => 'Sub'
  )

  has_many :links

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :require_current_user!

  def new
    render :new
  end

  def create
    @link = Link.new(params[:link])
    @link.user_id = current_user.id

    if @link.save
      redirect_to link_url(@link)
    else
      flash[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
    render :show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
                params[:user][:username],
                params[:user][:password]
    )

    if @user.nil?
      flash[:errors] = ["Invalid Username/Password Combination"]
      redirect_to :new
    else
      log_in_user!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_filter :require_current_user!, :except =>[:create, :new]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  def index

  end

  def show
    @user = User.find(params[:id])
    render :show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    current_user = user
  end

  def logout_current_user!
    current_user = nil
    session[:session_token] = nil
  end

  def require_current_user!
    p current_user
    redirect_to new_session_url if current_user.nil?
  end

end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
	<%= link_to "Log Out", session_url, method: :delete %>
<% else %>
	<%= link_to "Log In", new_session_url %>
	<%= link_to "Sign Up", new_user_url %>
<% end %>

<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<%= error %>
	<% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/links/new.html.erb
<h2>Create a new link</h2>

<form action = "<%= links_url %>" method= "post">
	<input type= "hidden"
					name="authenticity_token"
					value="<%= form_authenticity_token %>">

	<label for="link_title">Title:</label>
	<input 	type="text"
					name="link[title]"
					id="link_title">
	<br>

	<label for="link_url">URL:</label>
	<input 	type="text"
					name="link[url]"
					id="link_url">
	<br>

	<label for="link_body">Body (optional):</label>
	<textarea name="link[body]" id="link_body"></textarea>

	<br>

	<input type="submit" value = "Submit Link" >
</form>

app/views/links/show.html.erb
<p><div>
	<%= link_to @link.title, @link.url %><br>
	<% unless @link.body.empty? %>
		<%= @link.body %>
	<% end %>
Submitted <%= distance_of_time_in_words(@link.created_at, Time.now) %> ago by <%= @link.user.username %>.<br>
</div><p>

	<%= link_to "Back to user page", user_url(current_user) %><br>
	<%= link_to "Add a link!", new_link_url %>

<!-- ADD SUBS AND COMMENTS -->

app/views/users/new.html.erb
<h1>Create a New User!</h1>

<form action = "<%= users_url %>" method= "post">
	<input type= "hidden"
					name="authenticity_token"
					value="<%= form_authenticity_token %>">

	<label for="user_username">Username:</label>
	<input 	type="text"
					name="user[username]"
					id="user_username">
	<br>

	<label for="user_email">Email:</label>
	<input 	type="text"
					name="user[email]"
					id="user_email">
	<br>

	<label for="user_password">Password:</label>
	<input 	type="password"
					name="user[password]"
					id="user_password">
	<br>

	<input type="submit" value = "Create New User" >
</form>

app/views/users/show.html.erb
<h1>Welcome to your user page, <%= @user.username %>!</h1>

<%= link_to "Add a link!", new_link_url %>
<br><br>
<% @user.links.each do |link| %>
 <%= link_to link.title, link.url %>
 Submitted <%= distance_of_time_in_words(link.created_at, Time.now) %> ago
 <br>
<% end %>